[package]
name = "go-outside"
version = "0.1.0"
authors = ["Christopher Lane Hinson <clanehin@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.1", features = ["json"] }
serde_json = "1.0.63"
regex = "1.4.3"
clap = "2.33.3"
futures = "0.3.13"
